let DHIS_BASE_API_URL = process.env.REACT_APP_DHIS_BASE_API_URL;
let APP_BASE_URL =
  process.env.REACT_APP_APP_BASE_URL || 'http://41.89.94.99:3000';
  let tb = [
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Levels list',
	  id: 'all__levels_list',
	  url: `${DHIS_BASE_API_URL}/organisationUnitLevels.json?paging=false&fields=name,level`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Organisation unit details',
	  id: 'all__org_unit_details',
	  local_url: `${APP_BASE_URL}/api/common/organisationUnit`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Counties list',
	  id: 'all__counties_list',
	  local_url: `${APP_BASE_URL}/api/common/counties`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:2&fields=id,name,level&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Subcounties list',
	  id: 'all__subcounties_list',
	  local_url: `${APP_BASE_URL}/api/common/subcounties`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:3&fields=id,name,level,parent&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Wards list',
	  id: 'all__wards_list',
	  local_url: `${APP_BASE_URL}/api/common/wards`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:4&fields=id,name,level,parent&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Facilities list',
	  id: 'all__facilities_list',
	  local_url: `${APP_BASE_URL}/api/common/facilities`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:5&fields=id,name,level,parent&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'CUs list',
	  id: 'all__cus_list',
	  local_url: `${APP_BASE_URL}/api/common/community-units`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?filter=level:eq:6&fields=id,name,level,parent&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'MFL codes',
	  id: 'all__mfl_codes',
	  local_url: `${APP_BASE_URL}/api/common/mfl-codes`,
	  url: `${DHIS_BASE_API_URL}/organisationUnits.json?fields=id,code&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'User details',
	  id: 'all__user_details',
	  local_url: `${APP_BASE_URL}/api/common/defaults`,
	  url: `${DHIS_BASE_API_URL}/me.json`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Program Commodities',
	  id: 'all__commodities',
	  local_url: `${APP_BASE_URL}/api/common/commodities`,
	  url: `${DHIS_BASE_API_URL}/dataSets/RRnz4uPHXdl.json?fields=dataSetElements[dataElement[id,name]]`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Facilities assigned form',
	  id: 'all__mcf_orgunits',
	  local_url: `${APP_BASE_URL}/api/common/mcf-facilities`,
	  url: `${DHIS_BASE_API_URL}/dataSets.json?fields=id,name,organisationUnits[id,name,code,level]&filter=id:ilike:RRnz4uPHXdl&paging=false`,
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Global',
	  level: 'All',
	  name: 'Expected Reports',
	  id: 'all__expected_reports',
	  local_url: `${APP_BASE_URL}/api/common/expected-reports`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:RRnz4uPHXdl.EXPECTED_REPORTS`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Dashboard',
	  level: 'All',
	  name: 'Stock Status',
	  id: 'all__stock_status',
	  local_url: `${APP_BASE_URL}/api/dashboard/stockstatus`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:xgczUFGyigc.miM6uIJ2cWx;BfXSH6Bcgd8.TRw8Amoledr;odZ2IEYYLLK;uTL2bQuBPet.miM6uIJ2cWx;DNnJnuCr44Y.TRw8Amoledr;jfdSqd7NLIA;FHOOxDu3nm7.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;sIxKRMvOe3N;t2RYeKEC3GZ.miM6uIJ2cWx;EG8iaqKX2eq.TRw8Amoledr;KmkrgQ4rQYr;SHZCoTQreCb.miM6uIJ2cWx;leD1F35SGYm.TRw8Amoledr;W6k3lfLvhOv;D2ARbNsheQ5.miM6uIJ2cWx;j6EB9U0HB4P.TRw8Amoledr;mnlZIkbnAyN;vmVGakPHnky.miM6uIJ2cWx;VOOsfe4pPxC.TRw8Amoledr;RmPpZLFpKCa;UiVn7oWHu5a.miM6uIJ2cWx;foBquRqvLR5.TRw8Amoledr;AgsWXhnNknl;TgsVeYJe4sd.miM6uIJ2cWx;OhBNKe1NTeq.TRw8Amoledr;gDfyaC1i3Pk;mpWrQ4ix7JH.miM6uIJ2cWx;bpUp4QMn3Iu.TRw8Amoledr;YSqtr4bR8HK;xFjIqoej0Vg.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;nMyl1bo8gHi;MQSLLBJYb6C.miM6uIJ2cWx;MgQ2Bq8EEAq.TRw8Amoledr;yxXzwebCs5H;ZrNi0BSxGgl.miM6uIJ2cWx;i8PkCUh5Fik.TRw8Amoledr;Q6DsYuQM78Q;NWqlSUyRs0N.miM6uIJ2cWx;NuM1I0MnmoP.TRw8Amoledr;KlJIY3DChTK;kwnfBgJhCJW.miM6uIJ2cWx;zstDvWVPooz.TRw8Amoledr;Sx9eDjtxH38;HuMvibUeFYm.miM6uIJ2cWx;XUq7mFujyzS.TRw8Amoledr;H4G1qg7DfwD;rqskUi33Aeh.miM6uIJ2cWx;ATZnUs2RmVd.TRw8Amoledr;RMMja0YuBSs;B4bYJ15sZxC.miM6uIJ2cWx;wMqBG6RUQlh.TRw8Amoledr;OOGu4p8C96A;JWRG3jkirga.miM6uIJ2cWx;zm2U9nJQ2x2.TRw8Amoledr;VpC0Vj10ONs;XXAwPRaFQiR.miM6uIJ2cWx;ZIDG9tCleKX.TRw8Amoledr;V9NH9Jx5fGW;aozzplFbZEI.miM6uIJ2cWx;qqTaOHPl8MN.TRw8Amoledr;ZsFwZ1e0xSB;EOP7yDvTq1N.miM6uIJ2cWx;JjRwLmhZHbH.TRw8Amoledr;vwMuYZxmxJQ;ubJJUvbLPlb.miM6uIJ2cWx;S64D56OjB9w.TRw8Amoledr;FGYOyf3tav3;scOLKLz0M5o.miM6uIJ2cWx;yv1hvHcKgrH.TRw8Amoledr;PvSrkyUbU5p;OL2pzZfSOXc.miM6uIJ2cWx;L1My0KTxKBk.TRw8Amoledr;LiRzU6kGhmE;Upf4gANKIbJ.miM6uIJ2cWx;txAzEoC1TDB.TRw8Amoledr;mBKrtZygpJ3;Go66R2LwdrV.miM6uIJ2cWx;k1mVrXUuOnL.TRw8Amoledr;P3EaYdF0vQH;JYcKu03ERYv.miM6uIJ2cWx;XWIm2t6lglg.TRw8Amoledr;yP89wN45wAc;VIyAxA2ld9D.miM6uIJ2cWx;WoHyCSyeiPI.TRw8Amoledr;hVZkygpG1AF;TG2NpgqO1YH.miM6uIJ2cWx;UF6DA90Cfvo.TRw8Amoledr;TBjmUZRIGPS;lfDZYt4Ez2N.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;n1cnYsFuOau;DWLTXxDSx9H.miM6uIJ2cWx;Ak39JAb6v08.TRw8Amoledr;lK3MIHqfL4Q;Qa7iO8VWvnX.miM6uIJ2cWx;kiSFcMKPA8R.TRw8Amoledr;jQBcJ9SufRQ;G88hJum5k75.miM6uIJ2cWx;kSNOVxvgspz.TRw8Amoledr;Kmcmn4irtSs;OgmIXbdfk9W.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;kg03w5F1BaE;OQuugWBR6AD.miM6uIJ2cWx;VfvEWB7ukWJ.TRw8Amoledr;L7aYEvutgTS`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Filters: '',
	  Notes: ''
	},
	{
	  page: 'Dashboard',
	  level: 'All',
	  name: 'MOS by commodity',
	  id: 'all__mos_by_commodity',
	  local_url: `${APP_BASE_URL}/api/dashboard/mos-by-commodity`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:odZ2IEYYLLK;jfdSqd7NLIA;sIxKRMvOe3N;KmkrgQ4rQYr;W6k3lfLvhOv;mnlZIkbnAyN;RmPpZLFpKCa;AgsWXhnNknl;gDfyaC1i3Pk;YSqtr4bR8HK;nMyl1bo8gHi;yxXzwebCs5H;Q6DsYuQM78Q;KlJIY3DChTK;Sx9eDjtxH38;H4G1qg7DfwD;RMMja0YuBSs;OOGu4p8C96A;VpC0Vj10ONs;V9NH9Jx5fGW;ZsFwZ1e0xSB;vwMuYZxmxJQ;FGYOyf3tav3;PvSrkyUbU5p;LiRzU6kGhmE;mBKrtZygpJ3;P3EaYdF0vQH;yP89wN45wAc;hVZkygpG1AF;TBjmUZRIGPS;n1cnYsFuOau;lK3MIHqfL4Q;jQBcJ9SufRQ;Kmcmn4irtSs;kg03w5F1BaE;L7aYEvutgTS`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'Dashboard',
	  level: 'All',
	  name: 'Facilities stock status (count)',
	  id: 'all__facilities_stock_status',
	  local_url: `${APP_BASE_URL}/api/dashboard/facility-stock-status`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:HfGVoCZAwtd;nK8sqMAeQHY;ZcngDQJKiEg;wOKbEd8Dbi3;SSARcWY2Ge1;AX1co0SXobM;UUNwkYQhYgX;gEDxkvJmRAm`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: 5,
	  Filters: '',
	  Notes: ''
	},
	// Stock Status commodity-specific   
    {
        page: "Stock status",
        level: "County",
        name: "Rifapentine Tablets 150mg",
        id: "county__rifapentine_tablets_150mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;xgczUFGyigc.miM6uIJ2cWx;BfXSH6Bcgd8.TRw8Amoledr;odZ2IEYYLLK`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RH (75/50) Rifampicin/Isoniazid 75/50 Dispersible Tablet",
        id: "county__rh_75_50_rifampicin_isoniazid",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;uTL2bQuBPet.miM6uIJ2cWx;DNnJnuCr44Y.TRw8Amoledr;jfdSqd7NLIA`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RHZ (75/50/150) 3FDC RH Dispersible Tablet",
        id: "county__rh_z_75_50_150_3fdc",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;FHOOxDu3nm7.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;sIxKRMvOe3N`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Ethambutol Tablets - 400mg",
        id: "county__ethambutol_tablets_400mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;t2RYeKEC3GZ.miM6uIJ2cWx;EG8iaqKX2eq.TRw8Amoledr;KmkrgQ4rQYr`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Ethambutol HCL Tablets - 100mg (Dispersible)",
        id: "county__ethambutol_hcl_tablets_100mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;SHZCoTQreCb.miM6uIJ2cWx;leD1F35SGYm.TRw8Amoledr;W6k3lfLvhOv`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Pyrazinamide Tablets - 500mg",
        id: "county__pyrazinamide_tablets_500mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;D2ARbNsheQ5.miM6uIJ2cWx;j6EB9U0HB4P.TRw8Amoledr;mnlZIkbnAyN`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Rifampicin 300mg Capsules",
        id: "county__rifampicin_300mg_capsules",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;vmVGakPHnky.miM6uIJ2cWx;VOOsfe4pPxC.TRw8Amoledr;RmPpZLFpKCa`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Isoniazid Tablet 300mg",
        id: "county__isoniazid_tablet_300mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;UiVn7oWHu5a.miM6uIJ2cWx;foBquRqvLR5.TRw8Amoledr;AgsWXhnNknl`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Isoniazid Syrup 50mg/5ml 120ml",
        id: "county__isoniazid_syrup_50mg_5ml",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/gVp1KSFI69G`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;TgsVeYJe4sd.miM6uIJ2cWx;OhBNKe1NTeq.TRw8Amoledr;gDfyaC1i3Pk`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
	{
        page: "Stock status",
        level: "County",
        name: "VITAMIN B6-PYRIDOXINE 25MG FILM UNCOATED TABLET",
        id: "county__vitamin_b6_pyridoxine_25mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/iGa7exujrpJ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;mpWrQ4ix7JH.miM6uIJ2cWx;bpUp4QMn3Iu.TRw8Amoledr;YSqtr4bR8HK`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "VITAMIN B6-PYRIDOXINE 50 MG TABLETS",
        id: "county__vitamin_b6_pyridoxine_50mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/xFjIqoej0Vg`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;xFjIqoej0Vg.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;nMyl1bo8gHi`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "MB ADULT",
        id: "county__mb_adult",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/MQSLLBJYb6C`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;MQSLLBJYb6C.miM6uIJ2cWx;MgQ2Bq8EEAq.TRw8Amoledr;yxXzwebCs5H`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "MB CHILD",
        id: "county__mb_child",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/ZrNi0BSxGgl`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;ZrNi0BSxGgl.miM6uIJ2cWx;i8PkCUh5Fik.TRw8Amoledr;Q6DsYuQM78Q`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "PB ADULT",
        id: "county__pb_adult",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/NWqlSUyRs0N`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;NWqlSUyRs0N.miM6uIJ2cWx;NuM1I0MnmoP.TRw8Amoledr;KlJIY3DChTK`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "PB CHILD",
        id: "county__pb_child",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/kwnfBgJhCJW`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;kwnfBgJhCJW.miM6uIJ2cWx;zstDvWVPooz.TRw8Amoledr;Sx9eDjtxH38`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
	{
        page: 'Stock status',
        level: 'County',
        name: 'CAPREOMYCIN INJECTION (PFR) - 1GM',
        id: 'county__capreomycin_injection',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/HuMvibUeFYm`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;HuMvibUeFYm.miM6uIJ2cWx;XUq7mFujyzS.TRw8Amoledr;H4G1qg7DfwD`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'KANAMYCIN INJECTION 1G',
        id: 'county__kanamycin_injection',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/rqskUi33Aeh`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;rqskUi33Aeh.miM6uIJ2cWx;ATZnUs2RmVd.TRw8Amoledr;RMMja0YuBSs`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'CYCLOSERINE FILM COATED TABLETS - 250MG',
        id: 'county__cycloserine_tablets',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/B4bYJ15sZxC`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;B4bYJ15sZxC.miM6uIJ2cWx;wMqBG6RUQlh.TRw8Amoledr;OOGu4p8C96A`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'LEVOFLOXACIN TABLET 500MG',
        id: 'county__levofloxacin_tablet',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/JWRG3jkirga`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;JWRG3jkirga.miM6uIJ2cWx;zm2U9nJQ2x2.TRw8Amoledr;VpC0Vj10ONs`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'MOXIFLOXACIN 400MGS',
        id: 'county__moxifloxacin',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/XXAwPRaFQiR`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;XXAwPRaFQiR.miM6uIJ2cWx;ZIDG9tCleKX.TRw8Amoledr;V9NH9Jx5fGW`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'PROTHIONAMIDE FILM COATED TABLETS - 250MG',
        id: 'county__prothionamide_tablets',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/aozzplFbZEI`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;aozzplFbZEI.miM6uIJ2cWx;qqTaOHPl8MN.TRw8Amoledr;ZsFwZ1e0xSB`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'PARA-AMINOSALICYLIC ACID (PAS) SATCHET - 4GM',
        id: 'county__para_aminosalicylic_acid',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/EOP7yDvTq1N`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;EOP7yDvTq1N.miM6uIJ2cWx;JjRwLmhZHbH.TRw8Amoledr;vwMuYZxmxJQ`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: 'Stock status',
        level: 'County',
        name: 'BEDAQUILINE TABLET 100MG',
        id: 'county__bedaquiline_tablet',
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/ubJJUvbLPlb`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;ubJJUvbLPlb.miM6uIJ2cWx;S64D56OjB9w.TRw8Amoledr;FGYOyf3tav3`,
        default_period: 'LAST_MONTH',
        default_org_unit: 'HfVjCurKxh2',
        default_org_unit_level: 5,
        Notes: ''
    },
	{
        page: "Stock status",
        level: "County",
        name: "Clofazimine Capsules 100mg",
        id: "county__clofazimine_capsules",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/PvSrkyUbU5p`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;scOLKLz0M5o.miM6uIJ2cWx;yv1hvHcKgrH.TRw8Amoledr;PvSrkyUbU5p`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Linezolid Tablet 600mg",
        id: "county__linezolid_tablet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/LiRzU6kGhmE`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;OL2pzZfSOXc.miM6uIJ2cWx;L1My0KTxKBk.TRw8Amoledr;LiRzU6kGhmE`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Ready to Use Therapeutic Food (RUTF) 520-550 Kcal/100g (92g Sachet)",
        id: "county__rutf_sachet",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/mBKrtZygpJ3`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;Upf4gANKIbJ.miM6uIJ2cWx;txAzEoC1TDB.TRw8Amoledr;mBKrtZygpJ3`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Fortified Blended Food Adult",
        id: "county__fortified_blended_food_adult",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/P3EaYdF0vQH`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;Go66R2LwdrV.miM6uIJ2cWx;k1mVrXUuOnL.TRw8Amoledr;P3EaYdF0vQH`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Omeprazole Capsules - 20mg",
        id: "county__omeprazole_capsules",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/yP89wN45wAc`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;JYcKu03ERYv.miM6uIJ2cWx;XWIm2t6lglg.TRw8Amoledr;yP89wN45wAc`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RHZE TB Patient Packs 150/75/400/275 Film Coated Tablets",
        id: "county__rhze_tb_patient_packs",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/hVZkygpG1AF`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;VIyAxA2ld9D.miM6uIJ2cWx;WoHyCSyeiPI.TRw8Amoledr;hVZkygpG1AF`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RHZE [Patient Pack 150+75+400+275mg/Tab+R-H[Patient Pack]150+75mg/Tab",
        id: "county__rhze_patient_pack",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/TBjmUZRIGPS`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;TG2NpgqO1YH.miM6uIJ2cWx;UF6DA90Cfvo.TRw8Amoledr;TBjmUZRIGPS`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Vitamin B-6 - Pyridoxine HCL 50mg Tablets",
        id: "county__vitamin_b6_pyridoxine",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/n1cnYsFuOau`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;lfDZYt4Ez2N.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;n1cnYsFuOau`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "Rifapentine 300mg/Isoniazid 300mg Tablet",
        id: "county__rifapentine_isoniazid",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/lK3MIHqfL4Q`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;DWLTXxDSx9H.miM6uIJ2cWx;Ak39JAb6v08.TRw8Amoledr;lK3MIHqfL4Q`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "TB Patient Pack Category I & III 6M",
        id: "county__tb_patient_pack_category_i_iii",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/jQBcJ9SufRQ`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;Qa7iO8VWvnX.miM6uIJ2cWx;kiSFcMKPA8R.TRw8Amoledr;jQBcJ9SufRQ`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
	{
        page: "Stock status",
        level: "County",
        name: "RHZE Tablets - 150/75/400/275mg",
        id: "county__rhze_tablets_150_75_400_275mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/Kmcmn4irtSs`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;G88hJum5k75.miM6uIJ2cWx;kSNOVxvgspz.TRw8Amoledr;Kmcmn4irtSs`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RHZ 75mg/50mg/150mg",
        id: "county__rhz_75mg_50mg_150mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/kg03w5F1BaE`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;OgmIXbdfk9W.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;kg03w5F1BaE`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },
    {
        page: "Stock status",
        level: "County",
        name: "RH 75mg/50mg",
        id: "county__rh_75mg_50mg",
        local_url: `${APP_BASE_URL}/api/county/stockstatus/one/L7aYEvutgTS`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;OQuugWBR6AD.miM6uIJ2cWx;VfvEWB7ukWJ.TRw8Amoledr;L7aYEvutgTS`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ''
    },

	// Stock Status-All Commodities
	{
	  page: 'Stock status all',
	  level: 'County',
	  name: 'All commodities',
	  id: 'county__all_commodities',
	  local_url: `${APP_BASE_URL}/api/county/stockstatus/all`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:xgczUFGyigc.miM6uIJ2cWx;BfXSH6Bcgd8.TRw8Amoledr;odZ2IEYYLLK;uTL2bQuBPet.miM6uIJ2cWx;DNnJnuCr44Y.TRw8Amoledr;jfdSqd7NLIA;FHOOxDu3nm7.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;sIxKRMvOe3N;t2RYeKEC3GZ.miM6uIJ2cWx;EG8iaqKX2eq.TRw8Amoledr;KmkrgQ4rQYr;SHZCoTQreCb.miM6uIJ2cWx;leD1F35SGYm.TRw8Amoledr;W6k3lfLvhOv;D2ARbNsheQ5.miM6uIJ2cWx;j6EB9U0HB4P.TRw8Amoledr;mnlZIkbnAyN;vmVGakPHnky.miM6uIJ2cWx;VOOsfe4pPxC.TRw8Amoledr;RmPpZLFpKCa;UiVn7oWHu5a.miM6uIJ2cWx;foBquRqvLR5.TRw8Amoledr;AgsWXhnNknl;TgsVeYJe4sd.miM6uIJ2cWx;OhBNKe1NTeq.TRw8Amoledr;gDfyaC1i3Pk;mpWrQ4ix7JH.miM6uIJ2cWx;bpUp4QMn3Iu.TRw8Amoledr;YSqtr4bR8HK;xFjIqoej0Vg.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;nMyl1bo8gHi;MQSLLBJYb6C.miM6uIJ2cWx;MgQ2Bq8EEAq.TRw8Amoledr;yxXzwebCs5H;ZrNi0BSxGgl.miM6uIJ2cWx;i8PkCUh5Fik.TRw8Amoledr;Q6DsYuQM78Q;NWqlSUyRs0N.miM6uIJ2cWx;NuM1I0MnmoP.TRw8Amoledr;KlJIY3DChTK;kwnfBgJhCJW.miM6uIJ2cWx;zstDvWVPooz.TRw8Amoledr;Sx9eDjtxH38;HuMvibUeFYm.miM6uIJ2cWx;XUq7mFujyzS.TRw8Amoledr;H4G1qg7DfwD;rqskUi33Aeh.miM6uIJ2cWx;ATZnUs2RmVd.TRw8Amoledr;RMMja0YuBSs;B4bYJ15sZxC.miM6uIJ2cWx;wMqBG6RUQlh.TRw8Amoledr;OOGu4p8C96A;JWRG3jkirga.miM6uIJ2cWx;zm2U9nJQ2x2.TRw8Amoledr;VpC0Vj10ONs;XXAwPRaFQiR.miM6uIJ2cWx;ZIDG9tCleKX.TRw8Amoledr;V9NH9Jx5fGW;aozzplFbZEI.miM6uIJ2cWx;qqTaOHPl8MN.TRw8Amoledr;ZsFwZ1e0xSB;EOP7yDvTq1N.miM6uIJ2cWx;JjRwLmhZHbH.TRw8Amoledr;vwMuYZxmxJQ;ubJJUvbLPlb.miM6uIJ2cWx;S64D56OjB9w.TRw8Amoledr;FGYOyf3tav3;scOLKLz0M5o.miM6uIJ2cWx;yv1hvHcKgrH.TRw8Amoledr;PvSrkyUbU5p;OL2pzZfSOXc.miM6uIJ2cWx;L1My0KTxKBk.TRw8Amoledr;LiRzU6kGhmE;Upf4gANKIbJ.miM6uIJ2cWx;txAzEoC1TDB.TRw8Amoledr;mBKrtZygpJ3;Go66R2LwdrV.miM6uIJ2cWx;k1mVrXUuOnL.TRw8Amoledr;P3EaYdF0vQH;JYcKu03ERYv.miM6uIJ2cWx;XWIm2t6lglg.TRw8Amoledr;yP89wN45wAc;VIyAxA2ld9D.miM6uIJ2cWx;WoHyCSyeiPI.TRw8Amoledr;hVZkygpG1AF;TG2NpgqO1YH.miM6uIJ2cWx;UF6DA90Cfvo.TRw8Amoledr;TBjmUZRIGPS;lfDZYt4Ez2N.miM6uIJ2cWx;iI3oxVgjWGS.TRw8Amoledr;n1cnYsFuOau;DWLTXxDSx9H.miM6uIJ2cWx;Ak39JAb6v08.TRw8Amoledr;lK3MIHqfL4Q;Qa7iO8VWvnX.miM6uIJ2cWx;kiSFcMKPA8R.TRw8Amoledr;jQBcJ9SufRQ;G88hJum5k75.miM6uIJ2cWx;kSNOVxvgspz.TRw8Amoledr;Kmcmn4irtSs;OgmIXbdfk9W.miM6uIJ2cWx;mFBgryfADaG.TRw8Amoledr;kg03w5F1BaE;OQuugWBR6AD.miM6uIJ2cWx;VfvEWB7ukWJ.TRw8Amoledr;L7aYEvutgTS`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'hfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'Reporting Rate',
	  level: 'County',
	  name: 'Reporting Rate Trend',
	  id: 'county__reporting_rate_trend',
	  local_url: `${APP_BASE_URL}/api/county/reportingrate/trend`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.REPORTING_RATE;iGa7exujrpJ.REPORTING_RATE_ON_TIME;nrhdE7iTGCk.REPORTING_RATE`,
	  default_period: 'LAST_12_MONTHS',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: 1,
	  Notes: ''
	},
	{
	  page: 'Reporting Rate',
	  level: 'County',
	  name: 'Reporting Rate Trend (latest subcounty)',
	  id: 'county__latest_reporting_rate_subcounty',
	  local_url: `${APP_BASE_URL}/api/county/reportingrate/latesttrend`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:RRnz4uPHXdl.REPORTING_RATE`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: 3,
	  Notes: ''
	},
  
	{
	  page: 'Reporting Rate',
	  level: 'County',
	  name: 'Facility Reporting Rate',
	  id: 'county__facility_reporting_rate',
	  local_url: `${APP_BASE_URL}/api/county/reportingrate/facility`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.ACTUAL_REPORTS;iGa7exujrpJ.EXPECTED_REPORTS`,
	  default_period: 'LAST_6_MONTHS',
	  default_org_unit: 'vvOK1BxTbet',
	  default_org_unit_level: 5,
	  Notes: ''
	},
	{
	  page: 'Reporting Rate',
	  level: 'County',
	  name: 'Subcounty Reporting Rate',
	  id: 'county__subcounty_reporting_rate',
	  local_url: `${APP_BASE_URL}/api/county/reportingrate/subcounty`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iGa7exujrpJ.ACTUAL_REPORTS;iGa7exujrpJ.EXPECTED_REPORTS`,
	  default_period: 'LAST_6_MONTHS',
	  default_org_unit: 'vvOK1BxTbet',
	  default_org_unit_level: 4,
	  Notes: ''
	},

	// Data Quality: Concordance
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RIFAPENTINE TABLETS 150MG",
		id: "county__dq_consistency_rifapentine_tablets_150mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/BfXSH6Bcgd8`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:BfXSH6Bcgd8.TRw8Amoledr;BfXSH6Bcgd8.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RH(75/50)  RIFAMPICIN/ISONIAZID  75/50  DISPERSIBLE TABLET",
		id: "county__dq_consistency_rh_75_50_rifampicin_isoniazid_75_50_dispersible_tablet",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/DNnJnuCr44Y`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:DNnJnuCr44Y.TRw8Amoledr;DNnJnuCr44Y.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RHZ(75/50/150)  3FDC RHZ  DISPERSIBLE TABLET",
		id: "county__dq_consistency_rhz_75_50_150_3fdc_rhz_dispersible_tablet",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/mFBgryfADaG`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mFBgryfADaG.TRw8Amoledr;mFBgryfADaG.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "ETHAMBUTOL TABLETS  - 400MG",
		id: "county__dq_consistency_ethambutol_tablets_400mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/EG8iaqKX2eq`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:EG8iaqKX2eq.TRw8Amoledr;EG8iaqKX2eq.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "ETHAMBUTOL HCL TABLETS  - 100MG(DISPERSIBLE)",
		id: "county__dq_consistency_ethambutol_hcl_tablets_100mg_dispersible",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/leD1F35SGYm`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:leD1F35SGYm.TRw8Amoledr;leD1F35SGYm.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "PYRAZINAMIDE TABLETS - 500MG",
		id: "county__dq_consistency_pirazinamide_tablets_500mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/j6EB9U0HB4P`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:j6EB9U0HB4P.TRw8Amoledr;j6EB9U0HB4P.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RIFAMPICIN 300MG CAPSULES",
		id: "county__dq_consistency_rifampicin_300mg_capsules",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VOOsfe4pPxC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VOOsfe4pPxC.TRw8Amoledr;VOOsfe4pPxC.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "ISONIAZID TABLET 300MG",
		id: "county__dq_consistency_isoniazid_tablet_300mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/foBquRqvLR5`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:foBquRqvLR5.TRw8Amoledr;foBquRqvLR5.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "ISONIAZID SYRUP 50MG/5ML 120ML",
		id: "county__dq_consistency_isoniazid_syrup_50mg_5ml_120ml",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/OhBNKe1NTeq`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:OhBNKe1NTeq.TRw8Amoledr;OhBNKe1NTeq.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RIFAMPICIN 150MG  DISPERSIBLE TABLETS",
		id: "county__dq_consistency_rifampicin_150mg_dispersible_tablets",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/HChbsEQU0rK`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:HChbsEQU0rK.TRw8Amoledr;HChbsEQU0rK.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
        page: "Data Quality: Concordance",
        level: "County",
        name: "VITAMIN B6-PYRIDOXINE 25MG FILM UNCOATED TABLET",
        id: "county__dq_consistency_vitamin_b6_pyridoxine_25mg_film_uncoated_tablet",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/bpUp4QMn3Iu`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:bpUp4QMn3Iu.TRw8Amoledr;bpUp4QMn3Iu.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "VITAMIN B6-PYRIDOXINE 50 MG TABLETS",
        id: "county__dq_consistency_vitamin_b6_pyridoxine_50_mg_tablets",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/iI3oxVgjWGS`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iI3oxVgjWGS.TRw8Amoledr;iI3oxVgjWGS.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "MB ADULT",
        id: "county__dq_consistency_mb_adult",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/MgQ2Bq8EEAq`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:MgQ2Bq8EEAq.TRw8Amoledr;MgQ2Bq8EEAq.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "MB CHILD",
        id: "county__dq_consistency_mb_child",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/i8PkCUh5Fik`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:i8PkCUh5Fik.TRw8Amoledr;i8PkCUh5Fik.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "PB ADULT",
        id: "county__dq_consistency_pb_adult",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/NuM1I0MnmoP`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:NuM1I0MnmoP.TRw8Amoledr;NuM1I0MnmoP.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "PB CHILD",
        id: "county__dq_consistency_pb_child",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/zstDvWVPooz`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:zstDvWVPooz.TRw8Amoledr;zstDvWVPooz.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "CAPREOMYCIN INJECTION (PFR) - 1GM",
        id: "county__dq_consistency_capreomycin_injection_pfr_1gm",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/XUq7mFujyzS`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:XUq7mFujyzS.TRw8Amoledr;XUq7mFujyzS.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "KANAMYCIN INJECTION 1G",
        id: "county__dq_consistency_kanamycin_injection_1g",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/ATZnUs2RmVd`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ATZnUs2RmVd.TRw8Amoledr;ATZnUs2RmVd.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "CYCLOSERINE FILM COATED TABLETS - 250MG",
        id: "county__dq_consistency_cycloserine_film_coated_tablets_250mg",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/wMqBG6RUQlh`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:wMqBG6RUQlh.TRw8Amoledr;wMqBG6RUQlh.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Concordance",
        level: "County",
        name: "LEVOFLOXACIN TABLET 500MG",
        id: "county__dq_consistency_levofloxacin_tablet_500mg",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/zm2U9nJQ2x2`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:zm2U9nJQ2x2.TRw8Amoledr;zm2U9nJQ2x2.Y2NaSMdjxsC`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "MOXIFLOXACIN 400MGS",
		id: "county__dq_consistency_moxifloxacin_400mgs",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/ZIDG9tCleKX.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ZIDG9tCleKX.TRw8Amoledr;ZIDG9tCleKX.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "PROTHIONAMIDE FILM COATED TABLETS - 250MG",
		id: "county__dq_consistency_prothionamide_film_coated_tablets_250mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/qqTaOHPl8MN.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qqTaOHPl8MN.TRw8Amoledr;qqTaOHPl8MN.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "PARA-AMINOSALICYLIC ACID (PAS) SATCHET - 4GM",
		id: "county__dq_consistency_para_aminosalicylic_acid_pas_satchet_4gm",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/JjRwLmhZHbH.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:JjRwLmhZHbH.TRw8Amoledr;JjRwLmhZHbH.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "BEDAQUILINE TABLET 100MG",
		id: "county__dq_consistency_bedaquiline_tablet_100mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/S64D56OjB9w.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:S64D56OjB9w.TRw8Amoledr;S64D56OjB9w.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "CLOFAZIMINE CAPSULES 100MG",
		id: "county__dq_consistency_clofazimine_capsules_100mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/yv1hvHcKgrH.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:yv1hvHcKgrH.TRw8Amoledr;yv1hvHcKgrH.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "LINEZOLID TABLET 600MG",
		id: "county__dq_consistency_linezolid_tablet_600mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/L1My0KTxKBk.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:L1My0KTxKBk.TRw8Amoledr;L1My0KTxKBk.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "READY TO USE THERAPEUTIC FOOD (RUTF) 520-550 KCAL/100G (92G SATCHET)",
		id: "county__dq_consistency_ready_to_use_therapeutic_food_rutf_520_550_kcal_100g_92g_satchet",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/txAzEoC1TDB.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:txAzEoC1TDB.TRw8Amoledr;txAzEoC1TDB.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "FORTIFIED BLENDED FOOD ADULT",
		id: "county__dq_consistency_fortified_blended_food_adult",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/k1mVrXUuOnL.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:k1mVrXUuOnL.TRw8Amoledr;k1mVrXUuOnL.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "OMEPRAZOLE CAPSULES - 20MG",
		id: "county__dq_consistency_omeprazole_capsules_20mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/XWIm2t6lglg.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:XWIm2t6lglg.TRw8Amoledr;XWIm2t6lglg.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RHZE TB PATIENT PACKS 150/75/400/275 FILM COATED TABLETS",
		id: "county__dq_consistency_rhze_tb_patient_packs_150_75_400_275_film_coated_tablets",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/WoHyCSyeiPI.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WoHyCSyeiPI.TRw8Amoledr;WoHyCSyeiPI.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RHZE [PATIENT PACK 150+75+400+275MG/TAB+R-H[PATIENT PACK]150+75MG/TAB",
		id: "county__dq_consistency_rhze_patient_pack_150_75_400_275mg_tab_r_h_patient_pack_150_75mg_tab",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/UF6DA90Cfvo.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:UF6DA90Cfvo.TRw8Amoledr;UF6DA90Cfvo.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "VITAMIN B-6 -PYRIDOXINE HCL 50 MG TABLETS",
		id: "county__dq_consistency_vitamin_b_6_pyridoxine_hcl_50_mg_tablets",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/iI3oxVgjWGS.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iI3oxVgjWGS.TRw8Amoledr;iI3oxVgjWGS.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RIFAPENTINE 300MG/ISONIAZID 300MG TABLET",
		id: "county__dq_consistency_rifapentine_300mg_isoniazid_300mg_tablet",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/Ak39JAb6v08.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Ak39JAb6v08.TRw8Amoledr;Ak39JAb6v08.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "TB PATIENT PACK CATEGORY I&III 6M",
		id: "county__dq_consistency_tb_patient_pack_category_i_iii_6m",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/kiSFcMKPA8R.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kiSFcMKPA8R.TRw8Amoledr;kiSFcMKPA8R.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RHZE TABLETS - 150/75/400/275MG",
		id: "county__dq_consistency_rhze_tablets_150_75_400_275mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/kSNOVxvgspz.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kSNOVxvgspz.TRw8Amoledr;kSNOVxvgspz.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RHZ 75MG/50MG/150MG",
		id: "county__dq_consistency_rh_z_75mg_50mg_150mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/mFBgryfADaG.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mFBgryfADaG.TRw8Amoledr;mFBgryfADaG.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Concordance",
		level: "County",
		name: "RH 75MG/50MG",
		id: "county__dq_consistency_rh_75mg_50mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VfvEWB7ukWJ.TRw8Amoledr`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VfvEWB7ukWJ.TRw8Amoledr;VfvEWB7ukWJ.Y2NaSMdjxsC`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},


	// Data Quality: Consistency
	{
		page: 'Data Quality: Consistency',
		level: 'County',
		name: 'RIFAPENTINE TABLETS 150MG',
		id: 'county__dq_consistency_rifapentine150MG',
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/BfXSH6Bcgd8`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:BfXSH6Bcgd8.Y2NaSMdjxsC;BfXSH6Bcgd8.SA7ZVWJWisS;BfXSH6Bcgd8.Vx8fG1bRxJp;BfXSH6Bcgd8.voMGxzxapMN;BfXSH6Bcgd8.e2os98CantY;BfXSH6Bcgd8.TRw8Amoledr`,
		default_period: 'LAST_MONTH',
		default_org_unit: 'HfVjCurKxh2',
		default_org_unit_level: 5,
		Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'RH(75/50) RIFAMPICIN/ISONIAZID 75/50 DISPERSIBLE TABLET',
	id: 'county__dq_consistency_rh_rifampicin_isoniazid_75_50_dispersible',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/DNnJnuCr44Y`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:DNnJnuCr44Y.Y2NaSMdjxsC;DNnJnuCr44Y.SA7ZVWJWisS;DNnJnuCr44Y.Vx8fG1bRxJp;DNnJnuCr44Y.voMGxzxapMN;DNnJnuCr44Y.e2os98CantY;DNnJnuCr44Y.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'RHZ(75/50/150) 3FDC RHZ DISPERSIBLE TABLET',
	id: 'county__dq_consistency_rhz_3fdc_rhz_dispersible',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/mFBgryfADaG`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mFBgryfADaG.Y2NaSMdjxsC;mFBgryfADaG.SA7ZVWJWisS;mFBgryfADaG.Vx8fG1bRxJp;mFBgryfADaG.voMGxzxapMN;mFBgryfADaG.e2os98CantY;mFBgryfADaG.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'ETHAMBUTOL TABLETS - 400MG',
	id: 'county__dq_consistency_ethambutol_tablets_400mg',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/EG8iaqKX2eq`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:EG8iaqKX2eq.Y2NaSMdjxsC;EG8iaqKX2eq.SA7ZVWJWisS;EG8iaqKX2eq.Vx8fG1bRxJp;EG8iaqKX2eq.voMGxzxapMN;EG8iaqKX2eq.e2os98CantY;EG8iaqKX2eq.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'ETHAMBUTOL HCL TABLETS - 100MG (DISPERSIBLE)',
	id: 'county__dq_consistency_ethambutol_hcl_tablets_100mg_dispersible',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/leD1F35SGYm`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:leD1F35SGYm.Y2NaSMdjxsC;leD1F35SGYm.SA7ZVWJWisS;leD1F35SGYm.Vx8fG1bRxJp;leD1F35SGYm.voMGxzxapMN;leD1F35SGYm.e2os98CantY;leD1F35SGYm.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'PYRAZINAMIDE TABLETS - 500MG',
	id: 'county__dq_consistency_pyrazinamide_tablets_500mg',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/j6EB9U0HB4P`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:j6EB9U0HB4P.Y2NaSMdjxsC;j6EB9U0HB4P.SA7ZVWJWisS;j6EB9U0HB4P.Vx8fG1bRxJp;j6EB9U0HB4P.voMGxzxapMN;j6EB9U0HB4P.e2os98CantY;j6EB9U0HB4P.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'RIFAMPICIN 300MG CAPSULES',
	id: 'county__dq_consistency_rifampicin_300mg_capsules',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VOOsfe4pPxC`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VOOsfe4pPxC.Y2NaSMdjxsC;VOOsfe4pPxC.SA7ZVWJWisS;VOOsfe4pPxC.Vx8fG1bRxJp;VOOsfe4pPxC.voMGxzxapMN;VOOsfe4pPxC.e2os98CantY;VOOsfe4pPxC.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'ISONIAZID TABLET 300MG',
	id: 'county__dq_consistency_isoniazid_tablet_300mg',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/foBquRqvLR5`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:foBquRqvLR5.Y2NaSMdjxsC;foBquRqvLR5.SA7ZVWJWisS;foBquRqvLR5.Vx8fG1bRxJp;foBquRqvLR5.voMGxzxapMN;foBquRqvLR5.e2os98CantY;foBquRqvLR5.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
	page: 'Data Quality: Consistency',
	level: 'County',
	name: 'ISONIAZID SYRUP 50MG/5ML 120ML',
	id: 'county__dq_consistency_isoniazid_syrup_50mg_5ml_120ml',
	local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/OhBNKe1NTeq`,
	url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:OhBNKe1NTeq.Y2NaSMdjxsC;OhBNKe1NTeq.SA7ZVWJWisS;OhBNKe1NTeq.Vx8fG1bRxJp;OhBNKe1NTeq.voMGxzxapMN;OhBNKe1NTeq.e2os98CantY;OhBNKe1NTeq.TRw8Amoledr`,
	default_period: 'LAST_MONTH',
	default_org_unit: 'HfVjCurKxh2',
	default_org_unit_level: 5,
	Notes: ''
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "VITAMIN B6-PYRIDOXINE 25MG FILM UNCOATED TABLET",
		id: "county__dq_consistency_vitaminB6_25MG",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/bpUp4QMn3Iu`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:bpUp4QMn3Iu.Y2NaSMdjxsC;bpUp4QMn3Iu.SA7ZVWJWisS;bpUp4QMn3Iu.Vx8fG1bRxJp;bpUp4QMn3Iu.voMGxzxapMN;bpUp4QMn3Iu.e2os98CantY;bpUp4QMn3Iu.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "VITAMIN B6-PYRIDOXINE 50 MG TABLETS",
		id: "county__dq_consistency_vitaminB6_50MG",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/iI3oxVgjWGS`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iI3oxVgjWGS.Y2NaSMdjxsC;iI3oxVgjWGS.SA7ZVWJWisS;iI3oxVgjWGS.Vx8fG1bRxJp;iI3oxVgjWGS.voMGxzxapMN;iI3oxVgjWGS.e2os98CantY;iI3oxVgjWGS.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "MB ADULT",
		id: "county__dq_consistency_mb_adult",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/MgQ2Bq8EEAq`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:MgQ2Bq8EEAq.Y2NaSMdjxsC;MgQ2Bq8EEAq.SA7ZVWJWisS;MgQ2Bq8EEAq.Vx8fG1bRxJp;MgQ2Bq8EEAq.voMGxzxapMN;MgQ2Bq8EEAq.e2os98CantY;MgQ2Bq8EEAq.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "MB CHILD",
		id: "county__dq_consistency_mb_child",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/i8PkCUh5Fik`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:i8PkCUh5Fik.Y2NaSMdjxsC;i8PkCUh5Fik.SA7ZVWJWisS;i8PkCUh5Fik.Vx8fG1bRxJp;i8PkCUh5Fik.voMGxzxapMN;i8PkCUh5Fik.e2os98CantY;i8PkCUh5Fik.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "PB ADULT",
		id: "county__dq_consistency_pb_adult",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/NuM1I0MnmoP`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:NuM1I0MnmoP.Y2NaSMdjxsC;NuM1I0MnmoP.SA7ZVWJWisS;NuM1I0MnmoP.Vx8fG1bRxJp;NuM1I0MnmoP.voMGxzxapMN;NuM1I0MnmoP.e2os98CantY;NuM1I0MnmoP.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "PB CHILD",
		id: "county__dq_consistency_pb_child",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/zstDvWVPooz`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:zstDvWVPooz.Y2NaSMdjxsC;zstDvWVPooz.SA7ZVWJWisS;zstDvWVPooz.Vx8fG1bRxJp;zstDvWVPooz.voMGxzxapMN;zstDvWVPooz.e2os98CantY;zstDvWVPooz.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "CAPREOMYCIN INJECTION (PFR) - 1GM",
		id: "county__dq_consistency_capreomycin_injection_pfr_1gm",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/XUq7mFujyzS`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:XUq7mFujyzS.Y2NaSMdjxsC;XUq7mFujyzS.SA7ZVWJWisS;XUq7mFujyzS.Vx8fG1bRxJp;XUq7mFujyzS.voMGxzxapMN;XUq7mFujyzS.e2os98CantY;XUq7mFujyzS.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "KANAMYCIN INJECTION 1G",
		id: "county__dq_consistency_kanamycin_injection_1g",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/ATZnUs2RmVd`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ATZnUs2RmVd.Y2NaSMdjxsC;ATZnUs2RmVd.SA7ZVWJWisS;ATZnUs2RmVd.Vx8fG1bRxJp;ATZnUs2RmVd.voMGxzxapMN;ATZnUs2RmVd.e2os98CantY;ATZnUs2RmVd.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "CYCLOSERINE FILM COATED TABLETS - 250MG",
		id: "county__dq_consistency_cycloserine_film_coated_tablets_250mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/wMqBG6RUQlh`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:wMqBG6RUQlh.Y2NaSMdjxsC;wMqBG6RUQlh.SA7ZVWJWisS;wMqBG6RUQlh.Vx8fG1bRxJp;wMqBG6RUQlh.voMGxzxapMN;wMqBG6RUQlh.e2os98CantY;wMqBG6RUQlh.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
        page: "Data Quality: Consistency",
        level: "County",
        name: "MOXIFLOXACIN 400MGS",
        id: "county__dq_consistency_moxifloxacin_400mgs",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/ZIDG9tCleKX`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:ZIDG9tCleKX.Y2NaSMdjxsC;ZIDG9tCleKX.SA7ZVWJWisS;ZIDG9tCleKX.Vx8fG1bRxJp;ZIDG9tCleKX.voMGxzxapMN;ZIDG9tCleKX.e2os98CantY;ZIDG9tCleKX.TRw8Amoledr`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "PROTHIONAMIDE FILM COATED TABLETS - 250MG",
        id: "county__dq_consistency_prothionamide_film_coated_tablets_250mg",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/qqTaOHPl8MN`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:qqTaOHPl8MN.Y2NaSMdjxsC;qqTaOHPl8MN.SA7ZVWJWisS;qqTaOHPl8MN.Vx8fG1bRxJp;qqTaOHPl8MN.voMGxzxapMN;qqTaOHPl8MN.e2os98CantY;qqTaOHPl8MN.TRw8Amoledr`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
    {
        page: "Data Quality: Consistency",
        level: "County",
        name: "PARA-AMINOSALICYLIC ACID (PAS) SATCHET - 4GM",
        id: "county__dq_consistency_para_aminosalicylic_acid_pas_sachet_4gm",
        local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/JjRwL7XH33g`,
        url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:JjRwL7XH33g.Y2NaSMdjxsC;JjRwL7XH33g.SA7ZVWJWisS;JjRwL7XH33g.Vx8fG1bRxJp;JjRwL7XH33g.voMGxzxapMN;JjRwL7XH33g.e2os98CantY;JjRwL7XH33g.TRw8Amoledr`,
        default_period: "LAST_MONTH",
        default_org_unit: "HfVjCurKxh2",
        default_org_unit_level: 5,
        Notes: ""
    },
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "BEDAQUILINE TABLET 100MG",
		id: "county__dq_consistency_bedaquiline_tablet_100mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/S64D56OjB9w`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:S64D56OjB9w.Y2NaSMdjxsC;S64D56OjB9w.SA7ZVWJWisS;S64D56OjB9w.Vx8fG1bRxJp;S64D56OjB9w.voMGxzxapMN;S64D56OjB9w.e2os98CantY;S64D56OjB9w.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "CLOFAZIMINE CAPSULES 100MG",
		id: "county__dq_consistency_clofazimine_capsules_100mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/yv1hvHcKgrH`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:yv1hvHcKgrH.Y2NaSMdjxsC;yv1hvHcKgrH.SA7ZVWJWisS;yv1hvHcKgrH.Vx8fG1bRxJp;yv1hvHcKgrH.voMGxzxapMN;yv1hvHcKgrH.e2os98CantY;yv1hvHcKgrH.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "LINEZOLID TABLET 600MG",
		id: "county__dq_consistency_linezolid_tablet_600mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/L1My0KTxKBk`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:L1My0KTxKBk.Y2NaSMdjxsC;L1My0KTxKBk.SA7ZVWJWisS;L1My0KTxKBk.Vx8fG1bRxJp;L1My0KTxKBk.voMGxzxapMN;L1My0KTxKBk.e2os98CantY;L1My0KTxKBk.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "READY TO USE THERAPEUTIC FOOD (RUTF) 520-550 KCAL/100G (92G SATCHET)",
		id: "county__dq_consistency_ready_to_use_therapeutic_food",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/txAzEoC1TDB`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:txAzEoC1TDB.Y2NaSMdjxsC;txAzEoC1TDB.SA7ZVWJWisS;txAzEoC1TDB.Vx8fG1bRxJp;txAzEoC1TDB.voMGxzxapMN;txAzEoC1TDB.e2os98CantY;txAzEoC1TDB.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "FORTIFIED BLENDED FOOD ADULT",
		id: "county__dq_consistency_fortified_blended_food_adult",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/k1mVrXUuOnL`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:k1mVrXUuOnL.Y2NaSMdjxsC;k1mVrXUuOnL.SA7ZVWJWisS;k1mVrXUuOnL.Vx8fG1bRxJp;k1mVrXUuOnL.voMGxzxapMN;k1mVrXUuOnL.e2os98CantY;k1mVrXUuOnL.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "OMEPRAZOLE CAPSULES - 20MG",
		id: "county__dq_consistency_omeprazole_capsules_20mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/V26TfIt49Ab`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:V26TfIt49Ab.Y2NaSMdjxsC;V26TfIt49Ab.SA7ZVWJWisS;V26TfIt49Ab.Vx8fG1bRxJp;V26TfIt49Ab.voMGxzxapMN;V26TfIt49Ab.e2os98CantY;V26TfIt49Ab.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RHZE TB PATIENT PACKS 150/75/400/275 FILM COATED TABLETS",
		id: "county__dq_consistency_rhze_tb_patient_packs_150_75_400_275",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/WoHyCSyeiPI`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:WoHyCSyeiPI.Y2NaSMdjxsC;WoHyCSyeiPI.SA7ZVWJWisS;WoHyCSyeiPI.Vx8fG1bRxJp;WoHyCSyeiPI.voMGxzxapMN;WoHyCSyeiPI.e2os98CantY;WoHyCSyeiPI.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RHZE [PATIENT PACK 150+75+400+275MG/TAB+R-H[PATIENT PACK]150+75MG/TAB",
		id: "county__dq_consistency_rhze_patient_pack_150_75_400_275mg_tab",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/UF6DA90Cfvo`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:UF6DA90Cfvo.Y2NaSMdjxsC;UF6DA90Cfvo.SA7ZVWJWisS;UF6DA90Cfvo.Vx8fG1bRxJp;UF6DA90Cfvo.voMGxzxapMN;UF6DA90Cfvo.e2os98CantY;UF6DA90Cfvo.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "VITAMIN B-6 -PYRIDOXINE HCL 50 MG TABLETS",
		id: "county__dq_consistency_vitamin_b6_pyridoxine_hcl_50_mg_tablets",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/iI3oxVgjWGS.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:iI3oxVgjWGS.Y2NaSMdjxsC;iI3oxVgjWGS.SA7ZVWJWisS;iI3oxVgjWGS.Vx8fG1bRxJp;iI3oxVgjWGS.voMGxzxapMN;iI3oxVgjWGS.e2os98CantY;iI3oxVgjWGS.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RIFAPENTINE 300MG/ ISONIAZID 300MG TABLET",
		id: "county__dq_consistency_rifapentine_300mg_isoniazid_300mg_tablet",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/Ak39JAb6v08.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Ak39JAb6v08.Y2NaSMdjxsC;Ak39JAb6v08.SA7ZVWJWisS;Ak39JAb6v08.Vx8fG1bRxJp;Ak39JAb6v08.voMGxzxapMN;Ak39JAb6v08.e2os98CantY;Ak39JAb6v08.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "TB PATIENT PACK CATEGORY I&III 6M",
		id: "county__dq_consistency_tb_patient_pack_category_i_iii_6m",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/kiSFcMKPA8R.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kiSFcMKPA8R.Y2NaSMdjxsC;kiSFcMKPA8R.SA7ZVWJWisS;kiSFcMKPA8R.Vx8fG1bRxJp;kiSFcMKPA8R.voMGxzxapMN;kiSFcMKPA8R.e2os98CantY;kiSFcMKPA8R.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RHZE TABLETS - 150/75/400/275MG",
		id: "county__dq_consistency_rhze_tablets_150_75_400_275mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/kSNOVxvgspz.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kSNOVxvgspz.Y2NaSMdjxsC;kSNOVxvgspz.SA7ZVWJWisS;kSNOVxvgspz.Vx8fG1bRxJp;kSNOVxvgspz.voMGxzxapMN;kSNOVxvgspz.e2os98CantY;kSNOVxvgspz.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RHZ 75MG/50MG/150MG",
		id: "county__dq_consistency_rhz_75mg_50mg_150mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/mFBgryfADaG.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:mFBgryfADaG.Y2NaSMdjxsC;mFBgryfADaG.SA7ZVWJWisS;mFBgryfADaG.Vx8fG1bRxJp;mFBgryfADaG.voMGxzxapMN;mFBgryfADaG.e2os98CantY;mFBgryfADaG.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	{
		page: "Data Quality: Consistency",
		level: "County",
		name: "RH 75MG/50MG",
		id: "county__dq_consistency_rh_75mg_50mg",
		local_url: `${APP_BASE_URL}/api/county/dataquality/consistency/VfvEWB7ukWJ.Y2NaSMdjxsC`,
		url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:VfvEWB7ukWJ.Y2NaSMdjxsC;VfvEWB7ukWJ.SA7ZVWJWisS;VfvEWB7ukWJ.Vx8fG1bRxJp;VfvEWB7ukWJ.voMGxzxapMN;VfvEWB7ukWJ.e2os98CantY;VfvEWB7ukWJ.TRw8Amoledr`,
		default_period: "LAST_MONTH",
		default_org_unit: "HfVjCurKxh2",
		default_org_unit_level: 5,
		Notes: ""
	},
	
	{
	  page: 'Accountability',
	  level: 'County',
	  name: 'Accountability',
	  id: 'county__accountability',
	  local_url: `${APP_BASE_URL}/api/county/accountability`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kiSFcMKPA8R.Y2NaSMdjxsC;kiSFcMKPA8R.Vx8fG1bRxJp;kiSFcMKPA8R.SA7ZVWJWisS;kiSFcMKPA8R.e2os98CantY;kiSFcMKPA8R.voMGxzxapMN;kiSFcMKPA8R.TRw8Amoledr;WoHyCSyeiPI.Y2NaSMdjxsC;WoHyCSyeiPI.Vx8fG1bRxJp;WoHyCSyeiPI.SA7ZVWJWisS;WoHyCSyeiPI.e2os98CantY;WoHyCSyeiPI.voMGxzxapMN;WoHyCSyeiPI.TRw8Amoledr;Xwat5Cw8bo0.Y2NaSMdjxsC;Xwat5Cw8bo0.Vx8fG1bRxJp;Xwat5Cw8bo0.SA7ZVWJWisS;Xwat5Cw8bo0.e2os98CantY;Xwat5Cw8bo0.voMGxzxapMN;Xwat5Cw8bo0.TRw8Amoledr;VfvEWB7ukWJ.Y2NaSMdjxsC;VfvEWB7ukWJ.Vx8fG1bRxJp;VfvEWB7ukWJ.SA7ZVWJWisS;VfvEWB7ukWJ.e2os98CantY;VfvEWB7ukWJ.voMGxzxapMN;VfvEWB7ukWJ.TRw8Amoledr;EG8iaqKX2eq.Y2NaSMdjxsC;EG8iaqKX2eq.Vx8fG1bRxJp;EG8iaqKX2eq.SA7ZVWJWisS;EG8iaqKX2eq.e2os98CantY;EG8iaqKX2eq.voMGxzxapMN;EG8iaqKX2eq.TRw8Amoledr;leD1F35SGYm.Y2NaSMdjxsC;leD1F35SGYm.Vx8fG1bRxJp;leD1F35SGYm.SA7ZVWJWisS;leD1F35SGYm.e2os98CantY;leD1F35SGYm.voMGxzxapMN;leD1F35SGYm.TRw8Amoledr;j6EB9U0HB4P.Y2NaSMdjxsC;j6EB9U0HB4P.Vx8fG1bRxJp;j6EB9U0HB4P.SA7ZVWJWisS;j6EB9U0HB4P.e2os98CantY;j6EB9U0HB4P.voMGxzxapMN;j6EB9U0HB4P.TRw8Amoledr;VOOsfe4pPxC.Y2NaSMdjxsC;VOOsfe4pPxC.Vx8fG1bRxJp;VOOsfe4pPxC.SA7ZVWJWisS;VOOsfe4pPxC.e2os98CantY;VOOsfe4pPxC.voMGxzxapMN;VOOsfe4pPxC.TRw8Amoledr;DNnJnuCr44Y.Y2NaSMdjxsC;DNnJnuCr44Y.Vx8fG1bRxJp;DNnJnuCr44Y.SA7ZVWJWisS;DNnJnuCr44Y.e2os98CantY;DNnJnuCr44Y.voMGxzxapMN;DNnJnuCr44Y.TRw8Amoledr`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: 1,
	  Notes: ''
	},
	{
	  page: 'Issues vs Receipts',
	  level: 'County',
	  name: 'Issues vs Receipts',
	  id: 'county__issues_vs_receipts',
	  local_url: `${APP_BASE_URL}/api/county/issuesvsreceipts`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kiSFcMKPA8R.kXaXqgog50o;EdcpaqKenMa.kXaXqgog50o;kSNOVxvgspz.kXaXqgog50o;SBKzD6J3Y6p.kXaXqgog50o;mFBgryfADaG.kXaXqgog50o;yEqi0i9Udcf.kXaXqgog50o;VfvEWB7ukWJ.kXaXqgog50o;nI1NoIHhFNB.kXaXqgog50o;EG8iaqKX2eq.kXaXqgog50o;pWfQoWwidaj.kXaXqgog50o;leD1F35SGYm.kXaXqgog50o;eIDeo8DyDqj.kXaXqgog50o;j6EB9U0HB4P.kXaXqgog50o;mwtiwoCyTjg.kXaXqgog50o;VOOsfe4pPxC.kXaXqgog50o;rtecB6TA0Bo.kXaXqgog50o;foBquRqvLR5.kXaXqgog50o;DWlifgpJQBy.kXaXqgog50o;OhBNKe1NTeq.kXaXqgog50o;iSb96Vl7ibE.kXaXqgog50o;bpUp4QMn3Iu.kXaXqgog50o;eZqcHd7ORdR.kXaXqgog50o;iI3oxVgjWGS.kXaXqgog50o;nS00RcjYcT4.kXaXqgog50o;MgQ2Bq8EEAq.kXaXqgog50o;m0RRDtMb2kO.kXaXqgog50o;i8PkCUh5Fik.kXaXqgog50o;unAQtebd6d5.kXaXqgog50o;NuM1I0MnmoP.kXaXqgog50o;x1IF4zpWitF.kXaXqgog50o;zstDvWVPooz.kXaXqgog50o;CYkTleN8mXC.kXaXqgog50o;XUq7mFujyzS.kXaXqgog50o;fWImdTfoLgm.kXaXqgog50o;ATZnUs2RmVd.kXaXqgog50o;EAReLDyBPbn.kXaXqgog50o;wMqBG6RUQlh.kXaXqgog50o;bdkVG3XuSRF.kXaXqgog50o;zm2U9nJQ2x2.kXaXqgog50o;LZl9Ii9nU69.kXaXqgog50o;ZIDG9tCleKX.kXaXqgog50o;vffha6d85KF.kXaXqgog50o;qqTaOHPl8MN.kXaXqgog50o;XcIyki5NSD6.kXaXqgog50o;JjRwLmhZHbH.kXaXqgog50o;a9jV4NySgbx.kXaXqgog50o;S64D56OjB9w.kXaXqgog50o;HcsrezQhWRZ.kXaXqgog50o;yv1hvHcKgrH.kXaXqgog50o;t3chtroqd8W.kXaXqgog50o;L1My0KTxKBk.kXaXqgog50o;hMNULr9Z2yr.kXaXqgog50o;txAzEoC1TDB.kXaXqgog50o;f9aBDSI8gK7.kXaXqgog50o;k1mVrXUuOnL.kXaXqgog50o;obibfBrFFbW.kXaXqgog50o;XWIm2t6lglg.kXaXqgog50o;TsOQ27GdmXh.kXaXqgog50o;WoHyCSyeiPI.kXaXqgog50o;NbwzqENAb9Y.kXaXqgog50o;UF6DA90Cfvo.kXaXqgog50o;blxxqqCShL3.kXaXqgog50o;BfXSH6Bcgd8.kXaXqgog50o;KQ3QrjGYEdy.kXaXqgog50o;DNnJnuCr44Y.kXaXqgog50o;FDbfTVG0suj.kXaXqgog50o;mFBgryfADaG.kXaXqgog50o;tmVHmwNIZh8.kXaXqgog50o;iI3oxVgjWGS.kXaXqgog50o;tuw0dTqX9ML.kXaXqgog50o;Ak39JAb6v08.kXaXqgog50o;NLp0yUzx6px.kXaXqgog50o`,
	  default_period: 'LAST_3_MONTHS',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: 1,
	  Notes: ''
	},
	{
	  page: 'National Stocks',
	  level: 'National',
	  name: 'National Summary',
	  id: 'national__summary_facility_mos',
	  local_url: `${APP_BASE_URL}/api/national/summary/facility-mos`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:HfGVoCZAwtd;ZcngDQJKiEg;nK8sqMAeQHY;wOKbEd8Dbi3;SSARcWY2Ge1;AX1co0SXobM;UUNwkYQhYgX;gEDxkvJmRAm`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'National Stocks',
	  level: 'National',
	  name: 'National Summary',
	  id: 'national__summary_pending_mos',
	  local_url: `${APP_BASE_URL}/api/national/summary/pending-mos`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:E8WZg2xUe6D;LzIEVzUpWIG;UW54RautAEK;V00M1X2mgCp;Rf9K17Q8KA5;ELorMg0kQhA;W1VReF5uwnI`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'National Stocks',
	  level: 'National',
	  name: 'National Summary',
	  id: 'national__summary_kemsa_mos',
	  local_url: `${APP_BASE_URL}/api/national/summary/kemsa-mos`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:A3hCPRmBEc1;VJjIApOdBDM;xifzJdZepGL;m5JchlPXYGh;AcHIhCDHQ5q;ImjyH2PKcrb;MqaP08m7qpB`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'National Stocks',
	  level: 'National',
	  name: 'National Stocks',
	  id: 'national__kemsa_summary',
	  local_url: `${APP_BASE_URL}/api/national/summary/kemsasummary`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:Aui7lNDOsSF.svPoNZ3VkVx;Aui7lNDOsSF.G3eMNWySdZq;Aui7lNDOsSF.Q9rPivWnD4K;Aui7lNDOsSF.HMTuusGLTUj;Aui7lNDOsSF.sEiFVVjqcfg;Kkh8ZtRWFmX.svPoNZ3VkVx;Kkh8ZtRWFmX.G3eMNWySdZq;Kkh8ZtRWFmX.Q9rPivWnD4K;Kkh8ZtRWFmX.HMTuusGLTUj;Kkh8ZtRWFmX.sEiFVVjqcfg;iZe9QHpC31Y.svPoNZ3VkVx;iZe9QHpC31Y.G3eMNWySdZq;iZe9QHpC31Y.Q9rPivWnD4K;iZe9QHpC31Y.HMTuusGLTUj;iZe9QHpC31Y.sEiFVVjqcfg;E7M967QxxFc.svPoNZ3VkVx;E7M967QxxFc.G3eMNWySdZq;E7M967QxxFc.Q9rPivWnD4K;E7M967QxxFc.HMTuusGLTUj;E7M967QxxFc.sEiFVVjqcfg;Wupc6TOJhcK.svPoNZ3VkVx;Wupc6TOJhcK.G3eMNWySdZq;Wupc6TOJhcK.Q9rPivWnD4K;Wupc6TOJhcK.HMTuusGLTUj;Wupc6TOJhcK.sEiFVVjqcfg;lZCba7Ijb7x.svPoNZ3VkVx;lZCba7Ijb7x.G3eMNWySdZq;lZCba7Ijb7x.Q9rPivWnD4K;lZCba7Ijb7x.HMTuusGLTUj;lZCba7Ijb7x.sEiFVVjqcfg;ALnonKSyDct.svPoNZ3VkVx;ALnonKSyDct.G3eMNWySdZq;ALnonKSyDct.Q9rPivWnD4K;ALnonKSyDct.HMTuusGLTUj;ALnonKSyDct.sEiFVVjqcfg;ZiLVFNkjwdB.svPoNZ3VkVx;ZiLVFNkjwdB.G3eMNWySdZq;ZiLVFNkjwdB.Q9rPivWnD4K;ZiLVFNkjwdB.HMTuusGLTUj;ZiLVFNkjwdB.sEiFVVjqcfg`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'National SOH Comparison',
	  level: 'National',
	  name: 'SOH Comparison',
	  id: 'national__soh_comparison',
	  local_url: `${APP_BASE_URL}/api/national/sohcomparison`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:uTL2bQuBPet.miM6uIJ2cWx;bvO1JwempGw.HMTuusGLTUj;DNnJnuCr44Y.TRw8Amoledr;t2RYeKEC3GZ.miM6uIJ2cWx;wd5ksSEr1R3.HMTuusGLTUj;EG8iaqKX2eq.TRw8Amoledr;SHZCoTQreCb.miM6uIJ2cWx;J7foGauP6u8.HMTuusGLTUj;leD1F35SGYm.TRw8Amoledr;D2ARbNsheQ5.miM6uIJ2cWx;PXdmwgspd95.HMTuusGLTUj;j6EB9U0HB4P.TRw8Amoledr;vmVGakPHnky.miM6uIJ2cWx;ubGtBbYyNFb.HMTuusGLTUj;VOOsfe4pPxC.TRw8Amoledr;UiVn7oWHu5a.miM6uIJ2cWx;iEKztMjhZwv.HMTuusGLTUj;foBquRqvLR5.TRw8Amoledr;TgsVeYJe4sd.miM6uIJ2cWx;YYf9sxcj352.HMTuusGLTUj;OhBNKe1NTeq.TRw8Amoledr;mpWrQ4ix7JH.miM6uIJ2cWx;XFzAHMPHe8N.HMTuusGLTUj;bpUp4QMn3Iu.TRw8Amoledr;xFjIqoej0Vg.miM6uIJ2cWx;QTwAOOg6H5a.HMTuusGLTUj;iI3oxVgjWGS.TRw8Amoledr;MQSLLBJYb6C.miM6uIJ2cWx;ETKvH2JaNSq.HMTuusGLTUj;MgQ2Bq8EEAq.TRw8Amoledr;ZrNi0BSxGgl.miM6uIJ2cWx;zI4G1pc6V9D.HMTuusGLTUj;i8PkCUh5Fik.TRw8Amoledr;NWqlSUyRs0N.miM6uIJ2cWx;Ngqwk9wHOj0.HMTuusGLTUj;NuM1I0MnmoP.TRw8Amoledr;kwnfBgJhCJW.miM6uIJ2cWx;ZLsYn47RGVr.HMTuusGLTUj;zstDvWVPooz.TRw8Amoledr;HuMvibUeFYm.miM6uIJ2cWx;wlvqlnoS2f1.HMTuusGLTUj;XUq7mFujyzS.TRw8Amoledr;rqskUi33Aeh.miM6uIJ2cWx;ycBr1cO2OYb.HMTuusGLTUj;ATZnUs2RmVd.TRw8Amoledr;B4bYJ15sZxC.miM6uIJ2cWx;ENwfrVDWG4X.HMTuusGLTUj;wMqBG6RUQlh.TRw8Amoledr;JWRG3jkirga.miM6uIJ2cWx;jB6DyZIIdjH.HMTuusGLTUj;zm2U9nJQ2x2.TRw8Amoledr;aozzplFbZEI.miM6uIJ2cWx;PEBfMXSUOYM.HMTuusGLTUj;qqTaOHPl8MN.TRw8Amoledr;EOP7yDvTq1N.miM6uIJ2cWx;oktEEqzKwZ8.HMTuusGLTUj;JjRwLmhZHbH.TRw8Amoledr;ubJJUvbLPlb.miM6uIJ2cWx;XYQ3qEleEDY.HMTuusGLTUj;S64D56OjB9w.TRw8Amoledr;scOLKLz0M5o.miM6uIJ2cWx;UucCUvHWG88.HMTuusGLTUj;yv1hvHcKgrH.TRw8Amoledr;OL2pzZfSOXc.miM6uIJ2cWx;WPiwZXopd3b.HMTuusGLTUj;L1My0KTxKBk.TRw8Amoledr;Upf4gANKIbJ.miM6uIJ2cWx;s7JOUdxKnUK.HMTuusGLTUj;txAzEoC1TDB.TRw8Amoledr;Go66R2LwdrV.miM6uIJ2cWx;onpLhtk9zFu.HMTuusGLTUj;k1mVrXUuOnL.TRw8Amoledr;lfDZYt4Ez2N.miM6uIJ2cWx;bE7JWCOkrbk.HMTuusGLTUj;iI3oxVgjWGS.TRw8Amoledr;DWLTXxDSx9H.miM6uIJ2cWx;y6DZi4U8Sbo.HMTuusGLTUj;Ak39JAb6v08.TRw8Amoledr;Qa7iO8VWvnX.miM6uIJ2cWx;CpO7h3oyW3b.HMTuusGLTUj;kiSFcMKPA8R.TRw8Amoledr`,
	  default_period: 'LAST_MONTH',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
	{
	  page: 'Issues vs Receipts',
	  level: 'National',
	  name: 'Issues vs Receipts',
	  id: 'national__issues_vs_receipts',
	  local_url: `${APP_BASE_URL}/api/national/issuesvsreceipts`,
	  url: `${DHIS_BASE_API_URL}/analytics.json?dimension=dx:kiSFcMKPA8R.kXaXqgog50o;EdcpaqKenMa.kXaXqgog50o;kSNOVxvgspz.kXaXqgog50o;SBKzD6J3Y6p.kXaXqgog50o;mFBgryfADaG.kXaXqgog50o;yEqi0i9Udcf.kXaXqgog50o;VfvEWB7ukWJ.kXaXqgog50o;nI1NoIHhFNB.kXaXqgog50o;EG8iaqKX2eq.kXaXqgog50o;pWfQoWwidaj.kXaXqgog50o;leD1F35SGYm.kXaXqgog50o;eIDeo8DyDqj.kXaXqgog50o;j6EB9U0HB4P.kXaXqgog50o;mwtiwoCyTjg.kXaXqgog50o;VOOsfe4pPxC.kXaXqgog50o;rtecB6TA0Bo.kXaXqgog50o;foBquRqvLR5.kXaXqgog50o;DWlifgpJQBy.kXaXqgog50o;OhBNKe1NTeq.kXaXqgog50o;iSb96Vl7ibE.kXaXqgog50o;bpUp4QMn3Iu.kXaXqgog50o;eZqcHd7ORdR.kXaXqgog50o;iI3oxVgjWGS.kXaXqgog50o;nS00RcjYcT4.kXaXqgog50o;MgQ2Bq8EEAq.kXaXqgog50o;m0RRDtMb2kO.kXaXqgog50o;i8PkCUh5Fik.kXaXqgog50o;unAQtebd6d5.kXaXqgog50o;NuM1I0MnmoP.kXaXqgog50o;x1IF4zpWitF.kXaXqgog50o;zstDvWVPooz.kXaXqgog50o;CYkTleN8mXC.kXaXqgog50o;XUq7mFujyzS.kXaXqgog50o;fWImdTfoLgm.kXaXqgog50o;ATZnUs2RmVd.kXaXqgog50o;EAReLDyBPbn.kXaXqgog50o;wMqBG6RUQlh.kXaXqgog50o;bdkVG3XuSRF.kXaXqgog50o;zm2U9nJQ2x2.kXaXqgog50o;LZl9Ii9nU69.kXaXqgog50o;ZIDG9tCleKX.kXaXqgog50o;vffha6d85KF.kXaXqgog50o;qqTaOHPl8MN.kXaXqgog50o;XcIyki5NSD6.kXaXqgog50o;JjRwLmhZHbH.kXaXqgog50o;a9jV4NySgbx.kXaXqgog50o;S64D56OjB9w.kXaXqgog50o;HcsrezQhWRZ.kXaXqgog50o;yv1hvHcKgrH.kXaXqgog50o;t3chtroqd8W.kXaXqgog50o;L1My0KTxKBk.kXaXqgog50o;hMNULr9Z2yr.kXaXqgog50o;txAzEoC1TDB.kXaXqgog50o;f9aBDSI8gK7.kXaXqgog50o;k1mVrXUuOnL.kXaXqgog50o;obibfBrFFbW.kXaXqgog50o;XWIm2t6lglg.kXaXqgog50o;TsOQ27GdmXh.kXaXqgog50o;WoHyCSyeiPI.kXaXqgog50o;NbwzqENAb9Y.kXaXqgog50o;UF6DA90Cfvo.kXaXqgog50o;blxxqqCShL3.kXaXqgog50o;BfXSH6Bcgd8.kXaXqgog50o;KQ3QrjGYEdy.kXaXqgog50o;DNnJnuCr44Y.kXaXqgog50o;FDbfTVG0suj.kXaXqgog50o;mFBgryfADaG.kXaXqgog50o;tmVHmwNIZh8.kXaXqgog50o;iI3oxVgjWGS.kXaXqgog50o;tuw0dTqX9ML.kXaXqgog50o;Ak39JAb6v08.kXaXqgog50o;NLp0yUzx6px.kXaXqgog50o`,
	  default_period: 'LAST_3_MONTHS',
	  default_org_unit: 'HfVjCurKxh2',
	  default_org_unit_level: '',
	  Notes: ''
	},
  ];
  module.exports = tb

